# Generated by Django 4.2.3 on 2023-07-31 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(null=True, upload_to='vehicle_images')),
                ('Variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicleapp.variant')),
            ],
        ),
    ]
