# Generated by Django 4.2.3 on 2023-07-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='color',
            field=models.CharField(choices=[('White', 'White'), ('Black', 'Black'), ('Green', 'Green'), ('Red', 'Red'), ('Yellow', 'Yellow'), ('Blue', 'Blue'), ('Brown', 'Brown'), ('Orange', 'Orange')], max_length=50),
        ),
    ]
