# Generated by Django 4.2.3 on 2023-08-08 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0005_alter_image_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to='brochures/'),
        ),
    ]
