# Generated by Django 4.2.3 on 2023-08-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0006_vehicle_brochure'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='default_image',
            field=models.ImageField(blank=True, null=True, upload_to='default_images/'),
        ),
    ]
