# Generated by Django 4.2.3 on 2023-08-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0010_remove_news_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='url_to_image',
            field=models.URLField(null=True),
        ),
    ]
