# Generated by Django 4.2.3 on 2023-08-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0016_testride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testride',
            name='customer_phone',
            field=models.IntegerField(),
        ),
    ]
