# Generated by Django 4.2.3 on 2023-08-22 11:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0021_testride_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testride',
            name='booking_reference',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True),
        ),
    ]
