# Generated by Django 4.2.3 on 2023-07-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
                ('brand', models.CharField(choices=[('brand1', 'Brand 1'), ('brand2', 'Brand 2')], max_length=20)),
                ('address', models.TextField()),
                ('district', models.CharField(choices=[('district1', 'District 1'), ('district2', 'District 2')], max_length=20)),
                ('state', models.CharField(choices=[('state1', 'State 1'), ('state2', 'State 2')], max_length=20)),
                ('pin_code', models.CharField(max_length=10)),
                ('country', models.CharField(choices=[('country1', 'Country 1'), ('country2', 'Country 2')], max_length=20)),
                ('field_experience', models.IntegerField()),
                ('num_staff', models.IntegerField()),
                ('sales_contact_no', models.CharField(max_length=20)),
                ('service_contact_no', models.CharField(max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
