# Generated by Django 4.2.3 on 2023-07-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_dealer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='website',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
