# Generated by Django 4.2.3 on 2023-07-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_alter_dealer_country_alter_dealer_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='state',
            field=models.CharField(choices=[('kerala', 'Kerala')], max_length=20),
        ),
    ]
