# Generated by Django 4.2.3 on 2023-08-10 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_remove_dealer_email_remove_dealer_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='is_verified',
        ),
    ]
