# Generated by Django 4.2.3 on 2023-08-07 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0003_alter_variant_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='Vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicleapp.vehicle'),
        ),
    ]
