# Generated by Django 4.2.3 on 2023-08-07 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0004_image_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='Variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicleapp.variant'),
        ),
    ]
