# Generated by Django 4.2.3 on 2023-08-10 07:58

from django.db import migrations, models
import vehicleapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0007_vehicle_default_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to='brochures/', validators=[vehicleapp.models.validate_brochure]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='default_image',
            field=models.ImageField(blank=True, null=True, upload_to='default_images/', validators=[vehicleapp.models.validate_default_image]),
        ),
    ]
