# Generated by Django 4.2.3 on 2023-08-21 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0009_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='created_at',
        ),
    ]
