# Generated by Django 4.2.3 on 2023-08-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0011_alter_news_description_alter_news_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(),
        ),
    ]
