# Generated by Django 4.2.3 on 2023-08-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0013_alter_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='url_to_image',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
