# Generated by Django 4.2.3 on 2023-08-22 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0017_alter_testride_customer_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testride',
        ),
    ]
