# Generated by Django 4.2.3 on 2023-08-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0018_delete_testride'),
    ]

    operations = [
        migrations.CreateModel(
            name='testride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('dealer', models.CharField(max_length=50)),
                ('dealer_email', models.EmailField(max_length=254)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_email', models.CharField(max_length=50)),
                ('customer_phone', models.IntegerField()),
            ],
        ),
    ]
