# Generated by Django 4.2.3 on 2023-08-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0020_alter_testride_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='testride',
            name='booking_status',
            field=models.CharField(default='Pending', max_length=50, null=True),
        ),
    ]
