# Generated by Django 4.2.3 on 2023-08-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0022_alter_testride_booking_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testride',
            name='booking_reference',
            field=models.CharField(max_length=50),
        ),
    ]
