# Generated by Django 4.2.3 on 2023-09-01 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0023_alter_testride_booking_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='testride',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
