# Generated by Django 4.2.3 on 2023-09-05 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0024_testride_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='Variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vehicleapp.variant'),
        ),
    ]
