# Generated by Django 4.2.3 on 2023-07-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_dealer_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='brand',
            field=models.CharField(choices=[('BMW', 'Brand 1'), ('brand2', 'Brand 2')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='country',
            field=models.CharField(choices=[('india', 'Country 1'), ('country2', 'Country 2')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='district',
            field=models.CharField(choices=[('calicut', 'District 1'), ('district2', 'District 2')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='state',
            field=models.CharField(choices=[('kerala', 'State 1'), ('state2', 'State 2')], max_length=20),
        ),
    ]
