# Generated by Django 4.2.3 on 2023-07-30 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0001_initial'),
        ('userapp', '0006_alter_dealer_brand_alter_dealer_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicleapp.brand'),
        ),
    ]
